const blindboxs = [
    {
        name:"Light Balloon",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "https://images.stockx.com/images/Pop-Mart-Twinkle-Twinkle-Be-a-Little-Star-Series-Little-Balloon-Figure.jpg?fit=fill&bg=FFFFFF&w=480&h=320&q=60&dpr=1&trim=color&updated_at=1750192757",
    },
    {
        name:"Little King",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"Wake up! Sleepyhead!",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: "$19.99",
        inStock: true,
        series: "Twinkle Twinkle Be a Little Star Series Figures",
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
{
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
    {
        name:"",
        price: ,
        inStock: ,
        series: ,
        img: "",
    },
]